### ISSUE TITLE
recording

### ISSUE THREAD

**Issue by TienLort** [videosdk-live/videosdk-rtc-react-native-call-trigger-example#1]
how can i record videocall an save it on Firebase

**Comment by ahmedbhesaniya97** [comment]
Hi @TienLort,
Regrettably, the current functionality does not support the storage of recordings in Firebase. However, you have the option to utilize prominent cloud platforms such as Google Cloud Platform (GCP), Amazon Web Services (AWS), or Microsoft Azure for this purpose.
